resources:
- name: repository
  type: git
  source:
    uri: https://github.com/bigangryrobot/fuze.git
    branch: master

jobs:
- name: build-fuze
  plan:
  - get: repository
    trigger: true
  - task: tests
    file: repository/ci-build.yaml