using System.Collections.Generic;
using System;

namespace Fuze
{
	/// <summary>
	/// This class is responsible for creating a structure which represents an ingress in a træfik cluster. 
	/// This is one of multiple services, designed for a pipeline, so that a kubernetes cluster namespace can be spun up for testing with services/ingress/pods or replicationcontroller.
	/// </summary>
	public class IngressGenerator
	{
		/// <summary>
		/// Creates an ingress rule for a given pipeline.
		/// Choices that have been made implicitly, are that træfik is running, and that the service is tested in 
		/// context of its correct placement (ie access goes through root on / )
		/// </summary>
		/// <param name="path">Path to save file</param>
		/// <param name="name">Ingress name</param>
		/// <param name="ingressName">Ingress name</param>
		public List<string> CreateIngress(string name, string hostName)
		{
			#region Conventions for ingress
			string ingressName = string.Format("{0}-ing", name);	
			string svcName = string.Format("{0}-svc", name);
			#endregion

			List<string> ingress = new List<string>();
			ingress = WriteIngressMetadata(ingress, ingressName, name);
			ingress = WriteIngressSpec(ingress, hostName, svcName);

			return ingress;
		}

		/// <summary>
		/// Writes in this format to file: 
		/// 
		/// apiVersion: extensions/v1beta1
		/// kind: Ingress
		/// metadata:
		///   name: ingress-name
		///   
		/// </summary>
		/// <param name="file">The structure of the file to write to, in this context its an ingress yml.</param>
		/// <param name="ingressName">Name for the ingress in the kubernetes cluster</param>
		List<string> WriteIngressMetadata(List<string> file, string ingressName,string name)
		{
			SharedMethods indent = new SharedMethods(); 
			file.Add("apiVersion: extensions/v1beta1");
			file.Add("kind: Ingress");
			file.Add("metadata:");
			file.Add(indent.Padding(1, string.Format("name: {0}", ingressName)));
			file.Add(indent.Padding(1, string.Format("namespace: {0}", name)));
			file.Add(indent.Padding(1, "annotations:"));
			file.Add(indent.Padding(2, "ingress.kubernetes.io/rewrite-target: /"));
			file.Add(indent.Padding(2, "kubernetes.io/ingress.class: \"traefik\""));
			file.Add(indent.Padding(1, "labels:"));
			file.Add(indent.Padding(2, "traeffik/balancer-name: private"));
			file.Add(indent.Padding(2, string.Format("app: {0}", name)));
			file.Add(indent.Padding(2, "autoGenerated: true"));
			file.Add(indent.Padding(2, string.Format("generated: {0}", DateTime.Now)));
			
			return file;
		}

		/// <summary>
		/// Writes in this format to file: 
		/// 
		/// spec:
		///   rules:
		///   - host: host-name
		/// 	http:
		/// 	  paths:
		///       - path: /
		///         backend:
		///           appName: name-svc
		/// 		  servicePort: 80
		/// 		  
		/// </summary>
		/// <param name="file">The structure of the file to write to, in this context its an ingress yml.</param>
		/// <param name="hostName">The web address to access the resource on</param>
		/// <param name="appName">The name of the service. This is directly dependant on the ServiceGenerator class.</param>
		List<string> WriteIngressSpec(List<string> file, string hostName, string appName)
		{
			SharedMethods indent = new SharedMethods();
			file.Add("spec:");
			file.Add(indent.Padding(1, "rules:"));
			file.Add(indent.Padding(1, string.Format("- host: {0}", hostName)));
			file.Add(indent.Padding(2, "http:"));
			file.Add(indent.Padding(3, "paths:"));
			file.Add(indent.Padding(3, "- path: /"));
			file.Add(indent.Padding(4, "backend:"));
			file.Add(indent.Padding(5, string.Format("appName: {0}", appName)));
			file.Add(indent.Padding(5, "servicePort: 80"));
			return file;
		}
	}
}