using System.Collections.Generic;
using System;

namespace Fuze
{
	/// <summary>
	/// This class is responsible for creating a structure which represents an namespace in a træfik cluster. 
	/// This is one of multiple services, designed for a pipeline, so that a kubernetes cluster namespace can be spun up for testing with services/namespace/pods or replicationcontroller.
	/// </summary>
	public class SecretMapGenerator
	{
		/// <summary>
		/// Creates an secretmap rule for a given pipeline.
		/// </summary>
		/// <param name="path">Path to save file</param>
		/// <param name="name">Ingress name</param>
		public List<string> CreateSecretMap(string appName, string envName, List<Dictionary<string,string>> secretMaps)
		{

			#region Conventions for secretmap
			string nameSpace = string.Format("{0}-{1}", appName, envName);
			#endregion

			List<string> file = new List<string>();
			file = WriteSecretMapMetadata(file, appName, envName);

			foreach (var secretMap in secretMaps) {
				foreach (var secret in secretMap) {

					#region Conventions for secretmap
					string keyName = string.Format("{0}-value", secret.Key);
					#endregion

					file = WriteSecretMapSpec(file, keyName, secret.Value);
				}
			}

			return file;
		}

		/// <summary>
		/// Writes in this format to file: 
		/// 
		/// apiVersion: v1
		/// kind: Secret
		/// metadata:
		///   name: key-value
		///   namespace: foo-env
		///   
		/// </summary>
		/// <param name="file">The structure of the file to write to, in this context its an service yml.</param>
		/// <param name="appName">Name for the service in the kubernetes cluster</param>
		List<string> WriteSecretMapMetadata(List<string> file, string appName, string nameSpace)
		{
			SharedMethods indent = new SharedMethods();
			file.Add("apiVersion: v1");
			file.Add("kind: SecretMap");
			file.Add("metadata:");
			file.Add(indent.Padding(1, string.Format("name: {0}", appName)));
			file.Add(indent.Padding(1, string.Format("namespace: {0}", nameSpace)));
			file.Add(indent.Padding(1, "labels:"));			
			file.Add(indent.Padding(2, string.Format("app: {0}", appName)));
			file.Add(indent.Padding(2, "autoGenerated: true"));
			file.Add(indent.Padding(2, string.Format("generated: {0}", DateTime.Now)));				

			return file;
		}

		/// <summary>
		/// Writes in this format to file: 
		/// 
		/// type: Opaque
		/// data:
  		///   key.name: key.value
		///  
		/// Note that the targetPort can be any chosen port, it just needs to map to the pod exposed port.
		/// </summary>
		/// <param name="file">The structure of the file to write to, in this context its an service yml.</param>
		/// <param name="targetPort">The pod exposed on the deployed pods.</param>
		/// <param name="deploymentName">Name for the deployment in kubernetes.</param>
		/// <param name="appName">Name for the service in the kubernetes cluster</param>
		List<string> WriteSecretMapSpec(List<string> file, string keyName, string value)
		{
			SharedMethods indent = new SharedMethods();
			file.Add("type: Opaque");
			file.Add("data:");
			file.Add(indent.Padding(1, string.Format("{0}:{1}", keyName, value)));

			return file;
		}
	}
}
