using System.Collections.Generic;
using System;

namespace Fuze
{
	/// <summary>
	/// This class is responsible for creating a structure which represents a service. 
	/// This is one of multiple services, designed for a pipeline, so that a kubernetes cluster namespace can be spun up for testing with services/ingress/pods or replicationcontroller.
	/// </summary>
	public class ServiceGenerator
	{
		/// <summary>
		/// Creates an ingress rule for a given pipeline.
		/// Choices that have been made implicitly, are that træfik is running, and that the service is tested in 
		/// context of its correct placement (ie access goes through root on / )
		/// </summary>
		/// <param name="path">Path to save file</param>
		/// <param name="name">Ingress name</param>
		public List<string> CreateService(string name)
		{
			#region Conventions
			string appName = string.Format("{0}-svc", name);
			string deploymentName = string.Format("{0}-deploy", name);
			#endregion

			List<string> service = new List<string>();
			service = WriteServiceMetadata(service, appName, name);
			service = WriteServiceSpec(service, deploymentName);

			return service;
		}

		/// <summary>
		/// Writes in this format to file: 
		/// 
		/// apiVersion: v1
		/// kind: Service
		/// metadata:
		///   name: service-name
		///   
		/// </summary>
		/// <param name="file">The structure of the file to write to, in this context its an service yml.</param>
		/// <param name="appName">Name for the service in the kubernetes cluster</param>
		List<string> WriteServiceMetadata(List<string> file, string appName, string name)
		{
			SharedMethods indent = new SharedMethods();
			file.Add("apiVersion: v1");
			file.Add("kind: Service");
			file.Add("metadata:");
			file.Add(indent.Padding(1, string.Format("name: {0}", appName)));
			file.Add(indent.Padding(1, string.Format("namespace: {0}", name)));
			file.Add(indent.Padding(1, "labels:"));
			file.Add(indent.Padding(2, "app: name"));
			file.Add(indent.Padding(2, "autoGenerated: true"));
			file.Add(indent.Padding(2, string.Format("generated: {0}", DateTime.Now)));
			
			return file;
		}

		/// <summary>
		/// Writes in this format to file: 
		/// 
		/// spec:
		///   ports:
		///     - port: 80
		///     targetPort: 80
		///   selector:
		///     run: deployment-name
		///   type: ClusterIP
		///  
		/// Note that the targetPort can be any chosen port, it just needs to map to the pod exposed port.
		/// </summary>
		/// <param name="file">The structure of the file to write to, in this context its an service yml.</param>
		/// <param name="targetPort">The pod exposed on the deployed pods.</param>
		/// <param name="deploymentName">Name for the deployment in kubernetes.</param>
		List<string> WriteServiceSpec(List<string> file, string deploymentName)
		{
			SharedMethods indent = new SharedMethods();
			file.Add("spec:");
			file.Add(indent.Padding(1, "ports:"));
			file.Add(indent.Padding(1, "- name: http"));
			file.Add(indent.Padding(2, "protocol: TCP"));
			file.Add(indent.Padding(2, "port: 80"));
			file.Add(indent.Padding(2, "targetPort: 1337"));
			file.Add(indent.Padding(1, "selector:"));
			file.Add(indent.Padding(2, string.Format("app: {0}", deploymentName)));
			file.Add(indent.Padding(1, "type: ClusterIP"));
			return file;
		}
	}
}

